export const preDefinedCategories = [
    "Electronics",
    "Mobiles",
    "Fashion",
    "Home & Furniture",
    "Appliances",
    "Beauty & Personal Care",
    "Toys & Baby Care",
    "Books & Stationery",
    "Sports & Fitness",
    "Grocery",
    "Health & Wellness",
    "Automotive",
    "Laptops & Computers",
    "TVs & Appliances",
    "Jewellery",
    "Home Decor & Festive Needs",
    "Bags, Wallets & Belts",
    "Footwear",
    "Watches",
    "Furniture",
    "Kitchen & Dining",
    "Home Improvement",
    "Cameras & Accessories",
    "Gaming",
    "Baby & Kids",
    "Pet Supplies",
    "Musical Instruments",
    "Tools & Hardware",
    "Office Supplies",
    "Industrial Supplies",
    "Travel & Luggage",
    "Movies, Music & Video Games",
    "Software",
    "Gift Cards"
];
